name: mvp3007
description: "Merchant demoApp"

# Prevent publishing to pub.dev.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  connectivity_plus: ^6.0.4
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  graphql_flutter: ^5.2.0-beta.7
  http: ^1.2.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    # - assets/images/
    - assets/env/
    - assets/dev/
    - path: assets/dev/images/
      flavors:
        - dev
    - path: assets/images/
      flavors:
        - prod
